[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.13.0"
config.workspace = true
diesel = "2.3.7"
dotenv = "0.15.0"
futures-util = "0.3.32"
serde.workspace = true
tokio.workspace = true
uuid.workspace = true
serde_json.workspace = true
common = { path = "../common" }
actix-jwt-auth-middleware = "0.5.0"
url.workspace = true

[dev-dependencies]
client = { path = "../client" }
tempfile.workspace = true
