[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.13.0"
config.workspace = true
diesel = { version = "2.3.7", features = [
    "chrono",
    "postgres",
    "r2d2",
    "uuid",
] }
futures-util = "0.3.32"
serde.workspace = true
tokio.workspace = true
uuid.workspace = true
serde_json.workspace = true
common = { path = "../common" }
url.workspace = true
sha2.workspace = true
rsa.workspace = true
dotenv = "0.15.0"
postcard.workspace = true
rand = "0.10.0"
chrono.workspace = true
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
fake = "5.1.0"
reqwest.workspace = true
actix-files = "0.6.10"
base64.workspace = true

[dev-dependencies]
client = { path = "../client" }
tempfile.workspace = true
